---
deployment:
  tasks:
    - export DEPLOYPATH=/home/iescinocedu/bolsaempleo.iescinoc.edu.co/
    - /bin/cp -R main $DEPLOYPATH
  post_deploy:
    - /usr/local/cpanel/3rdparty/bin/git checkout --theirs .