---
deployment:
  tasks:
      - export DEPLOYPATH=/home/iescinocedu/bolsaempleo.iescinoc.edu.co/
  post_deploy:
      - /usr/local/cpanel/3rdparty/bin/git checkout --theirs .
    # - /bin/cp index.html $DEPLOYPATH
    # - /bin/cp style.css $DEPLOYPATH