---
deployment:
  tasks:
    - export DEPLOYPATH=/home/iescinocedu/bolsaempleo.iescinoc.edu.co/
    - /bin/cp -R main $DEPLOYPATH
    - command: "echo 'Deploying changes...'"
metadata:
    name: "Ies cinoc"
    version: "1.0"
    author: "Danilo Grisalez"
    post_deploy:
    - /usr/local/cpanel/3rdparty/bin/git checkout --theirs .
    # - npm run test-api
    pre_deploy:
    - sudo yum install -y nodejs
    - sudo yum install -y npm
    # - sudo apt-get update
    # - sudo apt-get install -y nodejs
    # - sudo apt-get install -y npm
hooks:
  pre:
    - command: "echo 'Backing up files...'"
  post:
    - command: "echo 'Deployment complete.'"