---
deployment:
  tasks:
    - export DEPLOYPATH=/home/iescinocedu/bolsaempleo.iescinoc.edu.co/
    - /bin/cp -R main $DEPLOYPATH
    - newman run tests/Cinoc.postman_collection.json > report.txt
metadata:
    name: "Ies cinoc"
    version: "1.0"
    author: "Danilo Grisalez"
post_deploy:
    - /usr/local/cpanel/3rdparty/bin/git checkout --theirs .
    - command: npm run test-api
    - command: newman run tests/Cinoc.postman_collection.json > report.txt
pre_deploy:
hooks:
  pre:
    - command: "echo 'Backing up files...'"
  post:
    - command: "echo 'Deployment complete.'"